### PR TITLE
Add universal contributing and code of conduct docs

### PR DESCRIPTION
**Pull request by mdpiper**
This PR adds two documents:

1. instructions for contributors to a CSDMS repository, and 
2. a code of conduct that they should follow. 

The idea is that these documents could be universal---in any repository, we could copy/paste their text or just point to them. In practice, we'll probably need tweaks on a per-repository basis, but this could be handled with issue and pull request templates (such as what is done in Landlab).

### CODE REVIEW

**Comment by mdpiper** [comment]
This is @mcflugen's idea from awhile ago.

**Comment by mdpiper** [comment]
@mcflugen and @gantian127, please let me know what you think of this.

**Comment by gantian127** [comment]
@mdpiper The added documents look good to me. I have the following suggestions for your consideration. Thanks!
- Set the "welcome" repo as a "Pinned" repo so that people could easily find and look at these documents.
- In the README file, it maybe good to add a brief sentence and the a link for "Contributing" document.

**Comment by mdpiper** [comment]
@mcflugen I was likely being too cute in naming this repository "welcomes". What if I renamed it "project", as in a repository for CSDMS project files + the the CSDMS project forum?

**Pull request merged**
